/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedFieldsRouteImport } from './routes/_authenticated/fields'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedMandiSetupRouteImport } from './routes/_authenticated/mandi-setup'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedSoilRouteImport } from './routes/_authenticated/soil'
import { Route as AuthenticatedVarietiesRouteImport } from './routes/_authenticated/varieties'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedBuyerBrowseRouteImport } from './routes/_authenticated/buyer/browse'
import { Route as AuthenticatedBuyerOffersRouteImport } from './routes/_authenticated/buyer/offers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldsRoute = AuthenticatedFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMandiSetupRoute = AuthenticatedMandiSetupRouteImport.update({
  id: '/mandi-setup',
  path: '/mandi-setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoilRoute = AuthenticatedSoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVarietiesRoute = AuthenticatedVarietiesRouteImport.update({
  id: '/varieties',
  path: '/varieties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyerBrowseRoute =
  AuthenticatedBuyerBrowseRouteImport.update({
    id: '/buyer/browse',
    path: '/buyer/browse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyerOffersRoute =
  AuthenticatedBuyerOffersRouteImport.update({
    id: '/buyer/offers',
    path: '/buyer/offers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/mandi-setup': typeof AuthenticatedMandiSetupRoute
  '/market': typeof AuthenticatedMarketRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/sell': typeof AuthenticatedSellRoute
  '/soil': typeof AuthenticatedSoilRoute
  '/varieties': typeof AuthenticatedVarietiesRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/buyer/browse': typeof AuthenticatedBuyerBrowseRoute
  '/buyer/offers': typeof AuthenticatedBuyerOffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/mandi-setup': typeof AuthenticatedMandiSetupRoute
  '/market': typeof AuthenticatedMarketRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/sell': typeof AuthenticatedSellRoute
  '/soil': typeof AuthenticatedSoilRoute
  '/varieties': typeof AuthenticatedVarietiesRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/buyer/browse': typeof AuthenticatedBuyerBrowseRoute
  '/buyer/offers': typeof AuthenticatedBuyerOffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/fields': typeof AuthenticatedFieldsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/mandi-setup': typeof AuthenticatedMandiSetupRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/soil': typeof AuthenticatedSoilRoute
  '/_authenticated/varieties': typeof AuthenticatedVarietiesRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/_authenticated/buyer/browse': typeof AuthenticatedBuyerBrowseRoute
  '/_authenticated/buyer/offers': typeof AuthenticatedBuyerOffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/analytics'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/equipment'
    | '/expenses'
    | '/fields'
    | '/finance'
    | '/groups'
    | '/mandi-setup'
    | '/market'
    | '/orders'
    | '/profile'
    | '/schemes'
    | '/sell'
    | '/soil'
    | '/varieties'
    | '/weather'
    | '/buyer/browse'
    | '/buyer/offers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/analytics'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/equipment'
    | '/expenses'
    | '/fields'
    | '/finance'
    | '/groups'
    | '/mandi-setup'
    | '/market'
    | '/orders'
    | '/profile'
    | '/schemes'
    | '/sell'
    | '/soil'
    | '/varieties'
    | '/weather'
    | '/buyer/browse'
    | '/buyer/offers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/alerts'
    | '/_authenticated/analysis'
    | '/_authenticated/analytics'
    | '/_authenticated/assistant'
    | '/_authenticated/calendar'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipment'
    | '/_authenticated/expenses'
    | '/_authenticated/fields'
    | '/_authenticated/finance'
    | '/_authenticated/groups'
    | '/_authenticated/mandi-setup'
    | '/_authenticated/market'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/schemes'
    | '/_authenticated/sell'
    | '/_authenticated/soil'
    | '/_authenticated/varieties'
    | '/_authenticated/weather'
    | '/_authenticated/buyer/browse'
    | '/_authenticated/buyer/offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fields': {
      id: '/_authenticated/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof AuthenticatedFieldsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mandi-setup': {
      id: '/_authenticated/mandi-setup'
      path: '/mandi-setup'
      fullPath: '/mandi-setup'
      preLoaderRoute: typeof AuthenticatedMandiSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soil': {
      id: '/_authenticated/soil'
      path: '/soil'
      fullPath: '/soil'
      preLoaderRoute: typeof AuthenticatedSoilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/varieties': {
      id: '/_authenticated/varieties'
      path: '/varieties'
      fullPath: '/varieties'
      preLoaderRoute: typeof AuthenticatedVarietiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer/browse': {
      id: '/_authenticated/buyer/browse'
      path: '/buyer/browse'
      fullPath: '/buyer/browse'
      preLoaderRoute: typeof AuthenticatedBuyerBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer/offers': {
      id: '/_authenticated/buyer/offers'
      path: '/buyer/offers'
      fullPath: '/buyer/offers'
      preLoaderRoute: typeof AuthenticatedBuyerOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFieldsRoute: typeof AuthenticatedFieldsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedMandiSetupRoute: typeof AuthenticatedMandiSetupRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedSoilRoute: typeof AuthenticatedSoilRoute
  AuthenticatedVarietiesRoute: typeof AuthenticatedVarietiesRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedBuyerBrowseRoute: typeof AuthenticatedBuyerBrowseRoute
  AuthenticatedBuyerOffersRoute: typeof AuthenticatedBuyerOffersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFieldsRoute: AuthenticatedFieldsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedMandiSetupRoute: AuthenticatedMandiSetupRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedSoilRoute: AuthenticatedSoilRoute,
  AuthenticatedVarietiesRoute: AuthenticatedVarietiesRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedBuyerBrowseRoute: AuthenticatedBuyerBrowseRoute,
  AuthenticatedBuyerOffersRoute: AuthenticatedBuyerOffersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
